
[build]
  command = "npm run build"
  publish = "dist"

# Règles de redirection pour les applications SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration des en-têtes pour une meilleure sécurité et performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' *.googleapis.com *.gstatic.com *.googletagmanager.com *.zenomedia.com *.allorigins.win *.totalementactus.net *.firebase.com *.firebaseio.com *.firebaseapp.com; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' *.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.googletagmanager.com *.google-analytics.com *.gpteng.co; connect-src 'self' *.googleapis.com *.firebaseio.com *.firebaseapp.com *.totalementactus.net *.zenomedia.com *.allorigins.win wss://*.firebaseio.com;"
    
# Optimisation du cache pour les ressources statiques
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
