
[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

# Règles de redirection pour les applications SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Règles pour autoriser les requêtes CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

# Configuration des en-têtes pour une meilleure sécurité et performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' *.googleapis.com *.gstatic.com *.googletagmanager.com *.zenomedia.com *.allorigins.win *.totalementactus.net *.firebase.com *.firebaseio.com *.firebaseapp.com https://cdn.gpteng.co; media-src * blob:; img-src 'self' data: https: blob:; style-src 'self' 'unsafe-inline' *.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.googletagmanager.com *.google-analytics.com *.gpteng.co; connect-src 'self' *.googleapis.com *.firebaseio.com *.firebaseapp.com *.totalementactus.net *.zenomedia.com *.allorigins.win wss://*.firebaseio.com api.allorigins.win *.zeno.fm stream.zeno.fm;"
    
# Optimisation du cache pour les ressources statiques
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuration des variables d'environnement
[build.environment]
  NODE_VERSION = "18.20.7"
  NPM_VERSION = "10.8.2"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"

# Paramètres pour éviter les problèmes liés à ESM et CommonJS
[functions]
  node_bundler = "esbuild"
